### ISSUE TITLE
Разработать сценарий отправки списка

### ISSUE THREAD

**Issue by vkamiansky** [vkamiansky/yandex-dialogs-inventory#5]
Необходимо разработать сценарий отправки списка на почту пользователя. Возможно, почту можно взять из его аккаунта, а возможно, первый раз придётся попросить пользователя почту ввести. Этот сценарий может быть состыкован со сценарием вывода списка.

**Comment by maxPakin** [comment]
Получить почту не получится, нам даётся clientID, а не сам аккаунт. Более того, у одного аккаунта могут быть разные clientId. Но я написал в Поддержку Алисы по этому поводу, в скором времени ответят.

**Comment by maxPakin** [comment]
@vkamiansky Мне поддержка ответила по этому поводу
![Image](https://i.imgur.com/kOApeqZ.jpg)

**Comment by Portsel** [comment]
придется, видимо, адрес вводить в явном виде.
Если отправка не по голосовой команде, то это не критично

вс, 26 мая 2019 г., 11:58 Pakin <notifications@github.com>:

**Comment by vkamiansky** [comment]
С этим порядок. Пока поддержим отправку на почту только для устройств с возможностью текстового ввода.

**Comment by maxPakin** [comment]
Тогда надо добавить Command и Result соответствующих типов
